<Workspace Version="0.9.0.3067" X="56.5251662348697" Y="133.995163097128" zoom="0.784369328044827" Name="Curve.MidPoint" Description="Get the midpoint along the Curve" ID="17905fee-de0e-4722-9319-1785ecf384f3" Category="Landform.Geometry.Curve">
  <NamespaceResolutionMap>
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="List.Create" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.DSFunction guid="0074857b-5e21-4d04-b63e-db3ad3868fae" type="Dynamo.Nodes.DSFunction" nickname="Curve.PointAtDistance" x="588.682559692887" y="0" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtDistance@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel guid="ba81e566-71ff-4ab6-89fb-449291cfbf06" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="419.264716077608" y="62.6318038741693" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="x/2;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction guid="370da064-47d6-49a3-810b-5f9b9970b0cf" type="Dynamo.Nodes.DSFunction" nickname="Curve.Length" x="224.501807649907" y="62.7716879258595" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.Length" />
    <Dynamo.Nodes.Symbol guid="2cfb2bca-3e59-469e-9572-3775e66f3066" type="Dynamo.Nodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="curve" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="b456150c-65a4-45ca-82f0-b6dd8a600f56" type="Dynamo.Nodes.Output" nickname="Output" x="814.882559692887" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="Point" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="0074857b-5e21-4d04-b63e-db3ad3868fae" start_index="0" end="b456150c-65a4-45ca-82f0-b6dd8a600f56" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ba81e566-71ff-4ab6-89fb-449291cfbf06" start_index="0" end="0074857b-5e21-4d04-b63e-db3ad3868fae" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="370da064-47d6-49a3-810b-5f9b9970b0cf" start_index="0" end="ba81e566-71ff-4ab6-89fb-449291cfbf06" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2cfb2bca-3e59-469e-9572-3775e66f3066" start_index="0" end="0074857b-5e21-4d04-b63e-db3ad3868fae" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2cfb2bca-3e59-469e-9572-3775e66f3066" start_index="0" end="370da064-47d6-49a3-810b-5f9b9970b0cf" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-28.8392467498779" eyeY="79.0925903320313" eyeZ="-19.9677429199219" lookX="0.000919624872040004" lookY="-5.0539345741272" lookZ="-0.107669033110142" upX="0.00830153468996286" upY="0.235142096877098" upZ="-0.971925556659698" />
  </Cameras>
</Workspace>